import { EMPTY_INVENTORY } from '../../lib/ocean/content';
import type { OceanSnapshot } from '../../lib/ocean/types';

export const DEFAULT_SNAPSHOT: OceanSnapshot = {
  fps: 60,
  health: 100,
  stamina: 100,
  maxStamina: 100,
  accelerating: false,
  oxygen: 105,
  maxOxygen: 105,
  hunger: 100,
  water: 100,
  depth: 0,
  heading: 180,
  biome: 'Coral Paradise',
  weather: 'Calm',
  dayPhase: 'Dawn',
  nearbySite: 'Whisper Arch',
  nearbySiteDistance: 0,
  objective: 'Recover the damaged PDA on the reef below',
  objectiveAngle: 0,
  objectiveDistance: 0,
  objectiveLabel: 'Damaged PDA',
  inventory: { ...EMPTY_INVENTORY },
  crafted: [],
  logs: [],
  prompt: '',
  toast: '',
  inSub: false,
  subBattery: 100,
  crushDepth: 85,
  lightsOn: false,
  elapsed: 0,
  threatName: '',
  threatDistance: 0,
  threatAttacking: false,
  damageFlash: false,
  threatHealth: 0,
  threatMaxHealth: 0,
  threatIsBoss: false,
  activeWeapon: 'mining',
  weaponReady: true,
  specialWeaponReady: true,
  toolBattery: 100,
  toolTemperature: 18,
};
