import * as THREE from 'three';
import type { DashSnapshot } from './types';

type Obstacle = { mesh: THREE.Group; lane: number; kind: 'hurdle' | 'crystal'; hit: boolean };
type Options = { canvas: HTMLCanvasElement; onUpdate: (state: DashSnapshot) => void };
const lanes = [-2.25, 0, 2.25];

export class SkylineWorld {
  private renderer: THREE.WebGLRenderer; private scene = new THREE.Scene(); private camera = new THREE.PerspectiveCamera(58, 1, .1, 130); private runner = new THREE.Group(); private officer = new THREE.Group(); private obstacles: Obstacle[] = [];
  private keys = new Set<string>(); private lane = 1; private targetLane = 1; private frame = 0; private previous = 0; private distance = 0; private crystals = 0; private health = 3; private running = false; private speed = 13; private step = 0; private jumpVelocity = 0; private policeDistance = 6.3;
  constructor(private readonly options: Options) { this.renderer = new THREE.WebGLRenderer({ canvas: options.canvas, antialias: true, powerPreference: 'high-performance' }); this.renderer.setPixelRatio(Math.min(devicePixelRatio, 1.7)); this.renderer.shadowMap.enabled = true; this.renderer.outputColorSpace = THREE.SRGBColorSpace; this.makeWorld(); this.resize(); window.addEventListener('resize', this.resize); window.addEventListener('keydown', this.down); window.addEventListener('keyup', this.up); this.animate(0); }
  start() { this.distance = 0; this.crystals = 0; this.health = 3; this.speed = 13; this.lane = 1; this.targetLane = 1; this.jumpVelocity = 0; this.policeDistance = 6.3; this.runner.position.set(0, 0, 0); this.obstacles.forEach((item, index) => this.recycle(item, -15 - index * 6)); this.running = true; this.options.onUpdate({ score: 0, crystals: 0, health: 3, speed: 13, isJumping: false, policeDistance: 6.3, gameOver: false }); } pause(value: boolean) { this.running = !value; } dispose() { cancelAnimationFrame(this.frame); this.renderer.dispose(); window.removeEventListener('resize', this.resize); window.removeEventListener('keydown', this.down); window.removeEventListener('keyup', this.up); }
  private makeWorld() { this.scene.background = new THREE.Color(0x8ed1d5); this.scene.fog = new THREE.Fog(0x8ed1d5, 22, 100); this.scene.add(new THREE.HemisphereLight(0xf4fdff, 0x3f694f, 2)); const sun = new THREE.DirectionalLight(0xffedbd, 2.2); sun.position.set(-12, 20, 8); sun.castShadow = true; this.scene.add(sun); const grass = new THREE.Mesh(new THREE.PlaneGeometry(100, 180), new THREE.MeshStandardMaterial({ color: 0x52774c, roughness: 1 })); grass.rotation.x = -Math.PI / 2; grass.position.z = -40; this.scene.add(grass); const road = new THREE.Mesh(new THREE.BoxGeometry(8.2, .22, 180), new THREE.MeshStandardMaterial({ color: 0x384d59, roughness: .85 })); road.position.set(0, 0, -40); this.scene.add(road); for (const x of [-1.12, 1.12]) { const line = new THREE.Mesh(new THREE.BoxGeometry(.09, .03, 180), new THREE.MeshBasicMaterial({ color: 0xf6e7a1 })); line.position.set(x, .13, -40); this.scene.add(line); } this.makeRunner(); for (let index = 0; index < 17; index += 1) this.obstacles.push(this.makeObstacle(index)); this.camera.position.set(0, 5.1, 8.6); this.camera.lookAt(0, 1.1, -5); }
  private makeRunner() { const jacket = new THREE.MeshStandardMaterial({ color: 0x295f90, roughness: .62 }); const skin = new THREE.MeshStandardMaterial({ color: 0xc9865b, roughness: .75 }); const hair = new THREE.MeshStandardMaterial({ color: 0x211612, roughness: .9 }); const black = new THREE.MeshStandardMaterial({ color: 0x101b23, roughness: .55 }); const white = new THREE.MeshStandardMaterial({ color: 0xf5f4df, roughness: .5 }); const body = new THREE.Mesh(new THREE.CapsuleGeometry(.4, .82, 4, 10), jacket); body.position.y = 1.14; const head = new THREE.Mesh(new THREE.SphereGeometry(.32, 14, 10), skin); head.position.y = 1.8; const fringe = new THREE.Mesh(new THREE.SphereGeometry(.33, 14, 8, 0, Math.PI * 2, 0, 1.15), hair); fringe.position.y = 1.95; const glasses = new THREE.Mesh(new THREE.BoxGeometry(.5, .13, .06), black); glasses.position.set(0, 1.82, -.29); this.runner.add(body, head, fringe, glasses); [-.26, .26].forEach((x) => { const arm = new THREE.Mesh(new THREE.CapsuleGeometry(.1, .5, 3, 7), jacket); arm.position.set(x, 1.16, 0); arm.rotation.z = x * .5; const leg = new THREE.Mesh(new THREE.CapsuleGeometry(.13, .55, 3, 7), black); leg.position.set(x * .55, .4, 0); const shoe = new THREE.Mesh(new THREE.BoxGeometry(.23, .12, .42), white); shoe.position.set(x * .55, .09, -.09); this.runner.add(arm, leg, shoe); }); this.runner.traverse((part) => { if (part instanceof THREE.Mesh) part.castShadow = true; }); this.scene.add(this.runner); this.makeOfficer(); }
  private makeOfficer() { const blue = new THREE.MeshStandardMaterial({ color: 0x274d72, roughness: .7 }); const skin = new THREE.MeshStandardMaterial({ color: 0xb66c4e, roughness: .8 }); const black = new THREE.MeshStandardMaterial({ color: 0x151a1c, roughness: .8 }); const shirt = new THREE.Mesh(new THREE.CapsuleGeometry(.38, .95, 4, 10), blue); shirt.position.y = 1.1; const head = new THREE.Mesh(new THREE.SphereGeometry(.3, 12, 9), skin); head.position.y = 1.75; const cap = new THREE.Mesh(new THREE.CylinderGeometry(.34, .34, .15, 12), blue); cap.position.y = 2.04; const brim = new THREE.Mesh(new THREE.BoxGeometry(.45, .06, .22), blue); brim.position.set(0, 1.99, -.3); const badge = new THREE.Mesh(new THREE.CircleGeometry(.09, 6), new THREE.MeshBasicMaterial({ color: 0xf3cf56 })); badge.position.set(-.18, 1.32, -.38); const brow = new THREE.Mesh(new THREE.BoxGeometry(.28, .05, .04), black); brow.position.set(0, 1.86, -.29); brow.rotation.z = -.35; this.officer.add(shirt, head, cap, brim, badge, brow); [-.27, .27].forEach((x) => { const arm = new THREE.Mesh(new THREE.CapsuleGeometry(.1, .5, 3, 7), blue); arm.position.set(x, 1.13, 0); arm.rotation.z = x * .7; this.officer.add(arm); }); this.officer.traverse((part) => { if (part instanceof THREE.Mesh) part.castShadow = true; }); this.scene.add(this.officer); }
  private makeObstacle(index: number) { const crystal = index % 3 === 0; const group = new THREE.Group(); const material = new THREE.MeshStandardMaterial({ color: crystal ? 0x78dbdd : 0xdc7050, emissive: crystal ? 0x226a77 : 0x4e120d, emissiveIntensity: .35, roughness: .48 }); const mesh = new THREE.Mesh(crystal ? new THREE.OctahedronGeometry(.36) : new THREE.BoxGeometry(1.5, .55, .42), material); mesh.position.y = crystal ? 1.6 : .32; mesh.castShadow = true; group.add(mesh); if (!crystal) { const stripe = new THREE.Mesh(new THREE.BoxGeometry(1.54, .09, .44), new THREE.MeshBasicMaterial({ color: 0xffe273 })); stripe.position.y = .32; group.add(stripe); } const obstacle: Obstacle = { mesh: group, lane: index % 3, kind: crystal ? 'crystal' : 'hurdle', hit: false }; this.recycle(obstacle, -15 - index * 6); this.scene.add(group); return obstacle; }
  private recycle(item: Obstacle, start = -70 - Math.random() * 30) { item.lane = Math.floor(Math.random() * 3); item.mesh.position.set(lanes[item.lane], 0, start); item.hit = false; item.mesh.visible = true; }
  private animate = (time: number) => { this.frame = requestAnimationFrame(this.animate); const delta = Math.min(.04, (time - this.previous) / 1000 || 0); this.previous = time; if (this.running) this.update(delta); this.renderer.render(this.scene, this.camera); };
  private update(delta: number) { if (this.keys.has('a') || this.keys.has('arrowleft')) { this.targetLane = Math.max(0, this.lane - 1); this.keys.delete('a'); this.keys.delete('arrowleft'); } if (this.keys.has('d') || this.keys.has('arrowright')) { this.targetLane = Math.min(2, this.lane + 1); this.keys.delete('d'); this.keys.delete('arrowright'); } if ((this.keys.has(' ') || this.keys.has('arrowup')) && this.runner.position.y < .02) { this.jumpVelocity = 7.2; this.keys.delete(' '); this.keys.delete('arrowup'); } this.lane = this.targetLane; this.runner.position.x = THREE.MathUtils.damp(this.runner.position.x, lanes[this.targetLane], 12, delta); this.jumpVelocity -= 20 * delta; this.runner.position.y = Math.max(0, this.runner.position.y + this.jumpVelocity * delta); if (!this.runner.position.y) this.jumpVelocity = 0; this.step += delta * this.speed; this.runner.rotation.z = Math.sin(this.step * .75) * .03; this.speed = Math.min(26, 13 + this.distance / 145); this.distance += this.speed * delta;
    this.obstacles.forEach((item) => { item.mesh.position.z += this.speed * delta; item.mesh.rotation.y += item.kind === 'crystal' ? delta * 3.2 : 0; if (item.mesh.position.z > 10) this.recycle(item); if (!item.hit && Math.abs(item.mesh.position.z) < .8 && Math.abs(item.mesh.position.x - this.runner.position.x) < .75) { if (item.kind === 'hurdle' && this.runner.position.y > .55) return; if (item.kind === 'crystal' && this.runner.position.y < .25) return; item.hit = true; item.mesh.visible = false; if (item.kind === 'crystal') this.crystals += 1; else { this.health -= 1; this.policeDistance = Math.max(1.2, this.policeDistance - 1.55); } } });
    this.policeDistance = Math.min(6.3, this.policeDistance + delta * .12); this.officer.position.x = THREE.MathUtils.damp(this.officer.position.x, this.runner.position.x, 6, delta); this.officer.position.z = this.policeDistance; this.officer.position.y = Math.abs(Math.sin(this.step * .8)) * .06; if (this.policeDistance < 1.45) this.health = 0; const gameOver = this.health <= 0; if (gameOver) this.running = false; this.options.onUpdate({ score: Math.floor(this.distance), crystals: this.crystals, health: Math.max(0, this.health), speed: Math.floor(this.speed), isJumping: this.runner.position.y > .02, policeDistance: this.policeDistance, gameOver }); }
  private down = (event: KeyboardEvent) => this.keys.add(event.key.toLowerCase()); private up = (event: KeyboardEvent) => this.keys.delete(event.key.toLowerCase()); private resize = () => { const { clientWidth, clientHeight } = this.renderer.domElement; this.renderer.setSize(clientWidth, clientHeight, false); this.camera.aspect = clientWidth / clientHeight; this.camera.updateProjectionMatrix(); };
}
