import type { CinematicPreset } from '../types';

export const atlasFinale: CinematicPreset = {
  kind: 'atlas-finale',
  duration: 17.4,
  entryEnd: 0.12,
  exitStart: 0.88,
  defaultSubject: 'ATLAS GATE',
  rail: [
    {
      position: [1.7, 2.45, -0.4],
      focus: [0, 0.25, -4],
      targetAnchor: 0,
      targetFocus: 0.015,
      radiusScale: 0,
      fov: 59,
      roll: -0.015,
    },
    {
      position: [10, 1.2, 5],
      focus: [0, 0, -3],
      targetAnchor: 0,
      targetFocus: 0.035,
      radiusScale: 0,
      fov: 50,
      roll: -0.07,
    },
    {
      position: [4, 13, -18],
      focus: [0, 0, 0],
      targetAnchor: 0.12,
      targetFocus: 0.23,
      radiusScale: 0.2,
      fov: 72,
      roll: 0.03,
    },
    {
      position: [-25, 4, -16],
      focus: [0, 0, 0],
      targetAnchor: 0.42,
      targetFocus: 0.68,
      radiusScale: 0.78,
      fov: 82,
      roll: 0.1,
    },
    {
      position: [-8, -16, 22],
      focus: [0, 0, 0],
      targetAnchor: 0.66,
      targetFocus: 0.94,
      radiusScale: 1.15,
      fov: 76,
      roll: 0.135,
    },
    {
      position: [24, 7, 13],
      focus: [0, 0, 0],
      targetAnchor: 0.73,
      targetFocus: 0.98,
      radiusScale: 1.25,
      fov: 68,
      roll: -0.06,
    },
    {
      position: [12, 2.4, -8],
      focus: [0, 0, 0],
      targetAnchor: 0.32,
      targetFocus: 0.62,
      radiusScale: 0.7,
      fov: 79,
      roll: -0.105,
    },
    {
      position: [-4, 2.3, -1.2],
      focus: [0, 0.25, -4],
      targetAnchor: 0.025,
      targetFocus: 0.085,
      radiusScale: 0.08,
      fov: 60,
      roll: 0,
    },
  ],
  shots: [
    { at: 0, id: 'departure', caption: 'ARCHIVE EVENT // WITNESS PROTOCOL' },
    { at: 0.16, id: 'companion', caption: 'THREE ECHOES SPEAKING AS ONE' },
    { at: 0.35, id: 'reveal', caption: '{subject} // SCALE UNRESOLVED' },
    { at: 0.57, id: 'orbit', caption: 'PRE-COLLAPSE GEOMETRY // AWAKENING' },
    { at: 0.75, id: 'threshold', caption: 'A DOOR BEYOND EVERY HUMAN CHART' },
    { at: 0.88, id: 'return', caption: 'LYRA // CROSSING AUTHORITY RESTORED' },
  ],
};
