import type { CinematicPreset } from '../types';

export const discoveryFlyby: CinematicPreset = {
  kind: 'discovery-flyby',
  duration: 9.8,
  entryEnd: 0.16,
  exitStart: 0.84,
  defaultSubject: 'UNIDENTIFIED CONTACT',
  rail: [
    {
      position: [1.8, 2.25, -1.1],
      focus: [0, 0.45, -4],
      targetAnchor: 0,
      targetFocus: 0.012,
      radiusScale: 0,
      fov: 62,
      roll: -0.025,
    },
    {
      position: [6.8, 1.4, 3.8],
      focus: [0, 0.1, -2.2],
      targetAnchor: 0,
      targetFocus: 0.025,
      radiusScale: 0,
      fov: 56,
      roll: -0.055,
    },
    {
      position: [4.4, 7.8, -12],
      focus: [0, 0, -3],
      targetAnchor: 0.08,
      targetFocus: 0.14,
      radiusScale: 0.22,
      fov: 68,
      roll: 0.018,
    },
    {
      position: [-11, 3.5, -9],
      focus: [0, 0, 0],
      targetAnchor: 0.38,
      targetFocus: 0.53,
      radiusScale: 0.72,
      fov: 74,
      roll: 0.06,
    },
    {
      position: [-5.2, -3.8, 8.5],
      focus: [0, 0, 0],
      targetAnchor: 0.58,
      targetFocus: 0.76,
      radiusScale: 1,
      fov: 70,
      roll: 0.085,
    },
    {
      position: [7.5, 2.4, 6],
      focus: [0, 0.2, -1.8],
      targetAnchor: 0.34,
      targetFocus: 0.56,
      radiusScale: 0.66,
      fov: 64,
      roll: -0.035,
    },
    {
      position: [-3.6, 2.1, -1],
      focus: [0, 0.35, -4],
      targetAnchor: 0.03,
      targetFocus: 0.08,
      radiusScale: 0.08,
      fov: 61,
      roll: 0,
    },
  ],
  shots: [
    { at: 0, id: 'departure', caption: 'LYRA // OPTICAL APERTURE OPENING' },
    { at: 0.2, id: 'companion', caption: 'CONTACT PARALLAX CONFIRMED' },
    { at: 0.41, id: 'reveal', caption: '{subject} // FIRST LIGHT' },
    { at: 0.62, id: 'orbit', caption: 'MAPPING UNCHARTED GEOMETRY' },
    { at: 0.84, id: 'return', caption: 'FLIGHT CONTROL // MANUAL AUTHORITY RESTORING' },
  ],
};
