import type { CinematicPreset } from '../types';

export const landingCompanion: CinematicPreset = {
  kind: 'landing-companion',
  duration: 11.6,
  entryEnd: 0.13,
  exitStart: 0.82,
  defaultSubject: 'SOLACE',
  rail: [
    {
      position: [2.2, 2, -0.6],
      focus: [0, 0.25, -4],
      targetAnchor: 0,
      targetFocus: 0.018,
      radiusScale: 0,
      fov: 60,
      roll: -0.02,
    },
    {
      position: [8.5, 0.8, 2.5],
      focus: [0, 0.1, -3],
      targetAnchor: 0.01,
      targetFocus: 0.035,
      radiusScale: 0.04,
      fov: 54,
      roll: -0.075,
    },
    {
      position: [6, -2.2, -13],
      focus: [0, 0, -4],
      targetAnchor: 0.1,
      targetFocus: 0.19,
      radiusScale: 0.18,
      fov: 67,
      roll: -0.03,
    },
    {
      position: [-15, 4.8, -8],
      focus: [0, 0, 0],
      targetAnchor: 0.34,
      targetFocus: 0.58,
      radiusScale: 0.72,
      fov: 75,
      roll: 0.045,
    },
    {
      position: [-6, 9, 16],
      focus: [0, -1.5, 0],
      targetAnchor: 0.58,
      targetFocus: 0.83,
      radiusScale: 1,
      fov: 79,
      roll: 0.095,
    },
    {
      position: [9, 3.5, 7],
      focus: [0, 0, -4],
      targetAnchor: 0.18,
      targetFocus: 0.35,
      radiusScale: 0.38,
      fov: 65,
      roll: -0.04,
    },
    {
      position: [-2.8, 1.9, -0.8],
      focus: [0, 0.35, -5],
      targetAnchor: 0.02,
      targetFocus: 0.07,
      radiusScale: 0.06,
      fov: 62,
      roll: 0,
    },
  ],
  shots: [
    { at: 0, id: 'departure', caption: 'DESCENT RECORD // EXTERNAL FEED' },
    { at: 0.18, id: 'companion', caption: 'LYRA RIDING THE ION WAKE' },
    { at: 0.42, id: 'reveal', caption: '{subject} // CLOUD DECK 61 KM' },
    { at: 0.63, id: 'threshold', caption: 'ATMOSPHERIC INTERFACE // COMMITTED' },
    { at: 0.82, id: 'return', caption: 'COCKPIT FEED // DESCENT CORRIDOR ACQUIRED' },
  ],
};
